export const marketplaceItems = [
  {
    id: "1",
    name: "Old Textbooks",
    price: 50,
    location: "University of Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/more_textbook.jpg",
  },
  {
    id: "2",
    name: "Air Fryer",
    price: 30,
    location: "University of Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/air_fryer.png",
  },
  {
    id: "3",
    name: "Nintendo Switch",
    price: 150,
    location: "University of Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/nintendo_switch.jpg",
  },
  {
    id: "4",
    name: "Old HP Laptop",
    price: 75,
    location: "University of Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/laptop.jpg",
  },
  {
    id: "5",
    name: "2006 Toyota Corolla",
    price: 1250,
    location: "Downtown Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/toyota_corolla.jpg",
  },
  {
    id: "6",
    name: "Old Bed",
    price: 65,
    location: "University of Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/fancy_bed.jpg",
  },
  {
    id: "7",
    name: "Old Textbooks",
    price: 150,
    location: "Downtown Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/old_books.jpg",
  },
  {
    id: "8",
    name: "Ikea Lamp",
    price: 12,
    location: "University of Calgary",
    picture: "https://d2epenzoyf672m.cloudfront.net/pfp/lamp.jpg",
  },
];
