version: "3.1"

services:
  db-campusbuddy:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
