import { z } from 'zod';
import * as generatedSchemas from '../prisma/generated/zod/index';

/**
 * These are manually created Zod schemas
 * Most schemas are based off of schemas generated by zod-prisma-types for consistency with thes prisma schemas and the database. Prisma schemas are considered the source of truth
 */

///////////////////////////////
// EVENT SCHEMAS
///////////////////////////////

/**
 * Create Verified Event Schema
 * omit not available on EventCustomValidatorsSchema -> z.ZodEffects
 * so we apply refine constraint to enforce endTime later than startTime here
 */
export const EventCreateSchema = generatedSchemas.EventSchema.omit({
    id: true,
    userId: true, // get from authtoken
    createdAt: true,
    imageId: true,
    organizationId: true, // get from req.params if creating verified event
}).refine((data) => data.endTime > data.startTime, {
    message: 'End time must be later than start time.',
    path: ['endTime'],
});

export type EventCreateInput = z.infer<typeof EventCreateSchema>;

/**
 * Update Event Schema
 * partial makes all fields optional
 */
export const EventUpdateSchema = generatedSchemas.EventSchema.partial();

export type EventUpdateInput = z.infer<typeof EventUpdateSchema>;

///////////////////////////////
// FILE SCHEMAS
///////////////////////////////

export const FileCreateSchema = generatedSchemas.FileSchema.omit({
    id: true,
    createdAt: true,
    uploadedBy: true,
    filePath: true, // path to cloud storage
});

export type FileCreateInput = z.infer<typeof FileCreateSchema>;

/////////////////////////////// s
// ORGANIZATION SCHEMAS
///////////////////////////////

// Create a new schema based on OrganizationSchema, omitting id and createdAt
export const OrganizationCreateSchema =
    generatedSchemas.OrganizationSchema.omit({
        id: true,
        createdAt: true,
    });

export type OrganizationCreateInput = z.infer<typeof OrganizationCreateSchema>;

/////////////////////////////// s
// UTILITY SCHEMAS
///////////////////////////////

// Schema for validating an ID integer parameter
export const IdParamSchema = z.object({
    id: z.coerce
        .number({
            invalid_type_error:
                'Invalid Id format. Must be a non-negative integer.',
        })
        .int()
        .positive()
        .safe(),
});
